
package com.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.service.util.Empleado;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SaveEmpleadoImpl", targetNamespace = "http://soap.service.com")
@XmlSeeAlso({
    com.service.client.ObjectFactory.class,
    com.service.client.ObjectFactory.class
})
public interface SaveEmpleadoImpl {


    /**
     * 
     * @param p
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "addEmpleadoReturn", targetNamespace = "http://soap.service.com")
    @RequestWrapper(localName = "addEmpleado", targetNamespace = "http://soap.service.com", className = "com.service.soap.AddEmpleado")
    @ResponseWrapper(localName = "addEmpleadoResponse", targetNamespace = "http://soap.service.com", className = "com.service.soap.AddEmpleadoResponse")
    public boolean addEmpleado(
        @WebParam(name = "p", targetNamespace = "http://soap.service.com")
        Empleado p);

}
