
package com.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SaveEmpleadoImplService", targetNamespace = "http://soap.service.com", wsdlLocation = "file:/C:/Users/Mauricio%20Esguerra/AppData/Local/Temp/tempdir15884834554897903538.tmp/SaveEmpleadoImpl_1.wsdl")
public class SaveEmpleadoImplService
    extends Service
{

    private final static URL SAVEEMPLEADOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAVEEMPLEADOIMPLSERVICE_EXCEPTION;
    private final static QName SAVEEMPLEADOIMPLSERVICE_QNAME = new QName("http://soap.service.com", "SaveEmpleadoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8086/Soap/services/SaveEmpleadoImpl?wsdll");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAVEEMPLEADOIMPLSERVICE_WSDL_LOCATION = url;
        SAVEEMPLEADOIMPLSERVICE_EXCEPTION = e;
    }

    public SaveEmpleadoImplService() {
        super(__getWsdlLocation(), SAVEEMPLEADOIMPLSERVICE_QNAME);
    }

    public SaveEmpleadoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAVEEMPLEADOIMPLSERVICE_QNAME, features);
    }

    public SaveEmpleadoImplService(URL wsdlLocation) {
        super(wsdlLocation, SAVEEMPLEADOIMPLSERVICE_QNAME);
    }

    public SaveEmpleadoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAVEEMPLEADOIMPLSERVICE_QNAME, features);
    }

    public SaveEmpleadoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaveEmpleadoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SaveEmpleadoImpl
     */
    @WebEndpoint(name = "SaveEmpleadoImpl")
    public SaveEmpleadoImpl getSaveEmpleadoImpl() {
        return super.getPort(new QName("http://soap.service.com", "SaveEmpleadoImpl"), SaveEmpleadoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaveEmpleadoImpl
     */
    @WebEndpoint(name = "SaveEmpleadoImpl")
    public SaveEmpleadoImpl getSaveEmpleadoImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.com", "SaveEmpleadoImpl"), SaveEmpleadoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAVEEMPLEADOIMPLSERVICE_EXCEPTION!= null) {
            throw SAVEEMPLEADOIMPLSERVICE_EXCEPTION;
        }
        return SAVEEMPLEADOIMPLSERVICE_WSDL_LOCATION;
    }

}
